[tool.poetry]
name = "tapas"
version = "1.1.3"
description = ""
authors = ["Florimond Houussiau <fhoussiau@turing.ac.uk>", "James Jordon", "Callum Mole <cmole@turing.ac.uk>", "Camila Rangel-Smith <crangelsmith@turing.ac.uk>", "James Geddes <jgeddes@turing.ac.uk>"]

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
matplotlib = ">=3.4.3"
palettable = "^3.3.0"
seaborn = ">=0.13,<0.15"
pandas = ">=2.2.2"
scipy = ">=1.8.0"
numpy = ">=1.23.5"
Sphinx = {version = ">=7,<9", optional = true}
sphinx-rtd-theme = {version = ">=2,<4", optional = true}
tqdm = "^4.64.0"
scikit-learn = ">=1.3.0"
mlflow = ">=3.1,<4"
torch = ">=2.0"
geomloss = ">=0.2.6"
xgboost = ">=2.0,<4"
plotly = ">=5,<8"

[tool.poetry.dev-dependencies]
spyder-kernels = "^2.1.0"
pytest = "^7.1.0"
Sphinx = ">=7,<9"
sphinx-rtd-theme = ">=2,<4"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme"]

[tool.poetry.scripts]
prive = "prive.run:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
